### PR TITLE
fix: prevent multiple, duplicate build-system entries

### LINKED ISSUE #1356: [BUG]
## Describe the bug

PR #1349 creates multiple duplicate `build-system` external references for some projects.

## To Reproduce

I do not have a shareable project that replicates the issue.  However, with the current implementation, I've seen the plugin produce records like:

```json
"externalReferences": [
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.internal.vcs/org/repo",
          "type": "vcs",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentVCS\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        }
      ]
```

## Expected behavior

There should not be duplicate `build-system` external references.

## Screenshots or output-paste

See above

## Environment

- _@cyclonedx/webpack-plugin_ version: 4.0.0
- webpack version: 5.95.0
- Node version: 22.12.0
- OS: osX

## Additional context

Proposed fix https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355 - uses the same mechanism to prevent multiple entries as the external references for VCS so I assumed there would be no issue.

## Contribution 

- [x] I am willing to provide a fix
- [ ] I will wait until somebody else fixes it

### PR DESCRIPTION
**Pull request by jeremylong**
PR #1349, for some projects, ends up creating multiple duplicate `build-system` external references. The fix is to ensure we have not already added an external reference of type: `build-system`.

With the current implementation, I've seen the plugin produce records like:

```json
"externalReferences": [
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.internal.vcs/org/repo",
          "type": "vcs",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentVCS\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        },
        {
          "url": "https://some.build.system.internal/job/88",
          "type": "build-system",
          "comment": "as declared via cyclonedx-webpack-plugin config \"rootComponentBuildSystem\""
        }
      ]
```

fixes #1356

### CODE REVIEW

**Comment by jkowalleck** [comment]
so you propose to add the setting only, if no build system was present? 

have you thought about the alternatives? 
I'd recommend creating an issue where we can discuss the situation, instead of dropping a out-of-nowhere PR.

Therefore, I'll mark this PR  as "draft" fdor now

**Comment by jeremylong** [comment]
Sorry - I always assume code is easier to use as a discussion point. This PR is using the same check as is already being done for VCS so I didn't think there would be a concern.

**Comment by jkowalleck** [comment]
> This PR is using the same check as is already being done for VCS so I didn't think there would be a concern.

exactly. and i fond this debatable.
- The docs do nowhere say that they would only apply if no such thing existed before.
- an alternative would be to override an existing thing.

File: src/plugin.ts [hunk 1]
```diff
@@ -327,7 +327,11 @@ export class CycloneDxWebpackPlugin {
     if (component === undefined) { return }
     if (
       typeof this.rootComponentBuildSystem === 'string' &&
-      this.rootComponentBuildSystem.length > 0
+      this.rootComponentBuildSystem.length > 0 &&
+      !iterableSome(
+        component.externalReferences,
+        ref => ref.type === CDX.Enums.ExternalReferenceType.BuildSystem
```
Comment (jeremylong) [inline src/plugin.ts:333]: Don't add if it is the exact same URL:
```suggestion
        ref => ref.type === CDX.Enums.ExternalReferenceType.BuildSystem &&
          ref.url === this.rootComponentBuildSystem
```

**Comment by jeremylong** [comment]
Instead of overriding an existing value, the code should not add duplicate entries. See the [proposal above](https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355#discussion_r1932524638).

File: src/plugin.ts (hunk 1 above)
Comment (jkowalleck) [reply src/plugin.ts:333]: debatable. see https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355#issuecomment-2619521529

**Comment by jkowalleck** [comment]
> Instead of overriding an existing value, the code should not add duplicate entries. See the [proposal above](https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355#discussion_r1932524638).

and exactly this thing is debatable. see https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355#issuecomment-2619521529 

I mean, the original code came from you, now you've changed your mind about the implementation, or did no think it trough in the first place.
What if you changed you mind in a month, wanna PR another "bugfix"? 
From a maintainers perspective, I was sceptical about this feature before, but now I am even more sceptical about it. 
My original concern was, that this feature was already in there, and was taking data from the package manifest. And you tried to get in an additional feature to set this value dynamically (which is an understandable request).
And now you realize that you have the data twice, in the package manifest and in the dynamic setup at the same time. I told you so.

I am tending to tell you, that you should manage your manifest properly, to solve your use case, instead of changing code. 
How does this sound to you?

**Comment by jkowalleck** [comment]
Reminder for self: regardless whether the BuildSystem  implementation becomes an "override" or a conditional, this change would be a breaking change. 
not a stopper, just a remark/justification

**Comment by jeremylong** [comment]
I think you are conflating the VCS and Build-System. The build-system only originates from the `rootComponentBuildSystem` configuration of the plugin. The VCS could come from the package.json or the `rootComponentVCS` configuration.

The only thing I didn't think through is that the call to `addRootComponentExtRefs` could occur more than once on the root component.

**Comment by jkowalleck** [comment]
> I think you are conflating the VCS and Build-System. The build-system only originates from the `rootComponentBuildSystem` configuration of the plugin. The VCS could come from the package.json or the `rootComponentVCS` configuration.
> 
> The only thing I didn't think through is that the call to `addRootComponentExtRefs` could occur more than once on the root component.

you are right; i was wrong.
I need to thing this trough, again.

**Comment by jeremylong** [comment]
@jkowalleck I've been trying to figure out how to easily create a reproducible test for the problem I've encountered. Unfortunately, the only thing I've been able to come up with will be complicated. It would require installing a ServiceNow CLI, configuring the CLI to work with a Now instance, etc.

If you are really going to require a reproducer it will likely take a LOT of work - when the fix is to just prevent the addition of the exact same build-system URL. I'd suggest merging [my suggestion](https://github.com/CycloneDX/cyclonedx-webpack-plugin/pull/1355#discussion_r1932524638) above and squash and merge the PR. However, I do understand wanting processes to be followed around reproducers to prevent regressions, etc.

Thoughts?

File: src/plugin.ts (hunk 1 above)
Comment (jkowalleck) [reply src/plugin.ts:333]: debate done. all fine.

**Review by jkowalleck — APPROVED** [review]

**Comment by jkowalleck** [comment]
> Thoughts?

agree. Lets merge this in.

Tomorrow I'm on a long train journey, so I might have time to create a regression test for this case ;-)

**Comment by jkowalleck** [comment]
fixed via https://github.com/CycloneDX/cyclonedx-webpack-plugin/releases/tag/v4.0.1

**Comment by jeremylong** [comment]
Thank you!
